/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Backend */

#ifndef _Included_Backend
#define _Included_Backend
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Backend
 * Method:    calculate
 * Signature: (IIC)I
 */
JNIEXPORT jint JNICALL Java_Backend_calculate
  (JNIEnv *, jobject, jint, jint, jchar);

#ifdef __cplusplus
}
#endif
#endif
